# Generated by Django 2.2.14 on 2022-10-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodtests', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='lower',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='upper',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
